In [1]:
import pandas as pd

In [14]:
df=pd.read_csv('customers-100.csv')

In [15]:
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [5]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [16]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [7]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [17]:
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              3
Phone 2              4
Email                0
Subscription Date    0
Website              0
dtype: int64

In [21]:
df['newphone']=df['Phone 2'].fillna(+91-100)

In [28]:
df.head(100)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,newphone
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,397.884.0519x718
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,686-620-1820x944
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,(496)978-3969x58947
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,+1-813-324-8756
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,001-199-446-3860x3486
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,NaN,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,-9
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,605.413.3198
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,+1-632-666-7507x92121
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,001-869-452-0943x12424
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,NaN,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,783.639.1472

In [29]:
df=df.rename(columns={'newphone':'Changed_Phone'})

In [30]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Changed_Phone
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,397.884.0519x718
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,686-620-1820x944
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,(496)978-3969x58947
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,+1-813-324-8756
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,001-199-446-3860x3486
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,NaN,hhart@jensen.com,2022-01-30,http://hayes-perez.com/,-9
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/,605.413.3198
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/,+1-632-666-7507x92121
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/,001-869-452-0943x12424
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,NaN,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/,783.639.1472

In [31]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

In [32]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [33]:
df.to_csv('wine.csv')

In [35]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
pd.read_html(url)

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [38]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560